services:
  # This is the Bot!
  bot:
    container_name: "ahao-bot"
    # build from the Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7414:7414"
    volumes:
      - ./:/app/
    env_file:
      - .env
    # 當容器停止時自動重啟（非永久錯誤）
    restart: unless-stopped